---

- name: install rpms
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unzip

- name: Download terraform
  get_url:
    url: "{{ terraform_source }}"
    dest: "/root/terraform.zip"
    mode: 0644
    force: no
    owner: root
    group: root

- name: Unarchive terraform
  unarchive:
    src: /root/terraform.zip
    dest: /usr/sbin
    mode: 0755
    remote_src: yes
